
POST http://localhost:9091/SakilaApplication/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getActorById>
           <actorId>1</actorId>
         </jets:getActorById>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9091/SakilaApplication/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getAllActors></jets:getAllActors>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9091/SakilaApplication/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getActorByFirstName>
         <actorFirstName>messi</actorFirstName>
         </jets:getActorByFirstName>
    </soap:Body>
</soap:Envelope>


###

POST http://localhost:9091/SakilaApplication/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:createActor>
         <actor>
               <firstName>aya</firstName>
               <lastName>ali</lastName> 
         </actor>
         </jets:createActor>
    </soap:Body>
</soap:Envelope>
 
 
###
POST http://localhost:9091/SakilaApplication/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:updateActorById>
         <actorId>209</actorId>
          <actorFirstName>aya</actorFirstName>
         </jets:updateActorById>
    </soap:Body>
</soap:Envelope>
 

###
POST http://localhost:9091/SakilaApplication/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:deleteActorById>
          <actorId>209</actorId>
         </jets:deleteActorById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:9091/SakilaApplication/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getActorFilmsById>
          <actorId>1</actorId>
         </jets:getActorFilmsById>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9091/SakilaApplication/ws/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getFilmById>
           <filmId>1</filmId>
         </jets:getFilmById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:9091/SakilaApplication/ws/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getAllFilms></jets:getAllFilms>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9091/SakilaApplication/ws/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getFilmByLength>
          <filmLength>64</filmLength>
        </jets:getFilmByLength>
    </soap:Body>
</soap:Envelope>



###

POST http://localhost:9091/SakilaApplication/ws/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getFilmCategoryById>
          <filmId>1</filmId>
        </jets:getFilmCategoryById>
    </soap:Body>
</soap:Envelope>



###

POST http://localhost:9091/SakilaApplication/ws/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:geFilmActorsById>
          <filmId>1</filmId>
        </jets:geFilmActorsById>
    </soap:Body>
</soap:Envelope>


###

POST http://localhost:9091/SakilaApplication/ws/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getCategoryById>
           <categoryId>1</categoryId>
         </jets:getCategoryById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:9091/SakilaApplication/ws/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getAllCategories></jets:getAllCategories>
    </soap:Body>
</soap:Envelope>



###
POST http://localhost:9091/SakilaApplication/ws/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getCategoryFilmsById>
           <categoryId>10</categoryId>
         </jets:getCategoryFilmsById>
    </soap:Body>
</soap:Envelope>
