

POST http://localhost:9091/SakilaApplication/ws/country HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getCountryById>
           <countryId>1</countryId>
         </jets:getCountryById>
    </soap:Body>
</soap:Envelope>





###

POST http://localhost:9091/SakilaApplication/ws/country HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getCountryCities>
           <countryId>28</countryId>
         </jets:getCountryCities>
    </soap:Body>
</soap:Envelope>