


POST http://localhost:9091/SakilaApplication/ws/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getStoreById>
           <storeId>1</storeId>
         </jets:getStoreById>
    </soap:Body>
</soap:Envelope>


###


POST http://localhost:9091/SakilaApplication/ws/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getStoreStaff>
           <storeId>1</storeId>
         </jets:getStoreStaff>
    </soap:Body>
</soap:Envelope>


###


POST http://localhost:9091/SakilaApplication/ws/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://interfaces.servcies.jets.iti.gov/">
      <soap:Body>
        <jets:getStoreCustomer>
           <storeId>1</storeId>
         </jets:getStoreCustomer>
    </soap:Body>
</soap:Envelope>